### ISSUE TITLE
Feature request: recipe API for home feed

### ISSUE THREAD

**Issue by udeyrishi** [SmartFoodTracker/backend#3]
It'd be great if there was a `/:deviceId/recipes/` GET API that was a proxy for the `/recipes/` API, but customized for a particular device. It would return the recipes with the ingredients == the current inventory, and the other query options to some sane defaults. The response would then map 1-1 with the home recipes feed.

**Comment by udeyrishi** [comment]
Or maybe it should be `:userId/recipes`. We probably need users now...

**Comment by udeyrishi** [comment]
As discussed on messenger, this will look up the user preferences based on the user Id, find the deviceId for the user, find the inventory for that device, use that as the ingredient list. It can potentially use some other stored preferences as defaults

**Comment by ahoskins** [comment]
add an endpoint: `/:userId/recipes` that looks up the ingredients for the user. In the future, will add things like stored prefs to it to make it smarter.
