### ISSUE TITLE
ID for recipes?

### ISSUE THREAD

**Issue by udeyrishi** [SmartFoodTracker/backend#5]
It'd be great if the recipe object has a unique ID, and then you can retrieve it by GET `recipe/:id`. Does spoonacular expose such IDs? That'll help in communicating the selected recipe when going from the home list to the details page.

**Comment by ahoskins** [comment]
closed in 40050365cbfea1f80fa1a7651a886a66d3fd55df

**Comment by ahoskins** [comment]
will make the get recipe/:id in another commit

**Comment by ahoskins** [comment]
endpoint in 24413342d34e22bc58b6cef9407f95a83346f3a7
