### ISSUE TITLE
The field "totalPages" in recipe responses is incorrect

### ISSUE THREAD

**Issue by udeyrishi** [SmartFoodTracker/backend#8]
All the responses say that the `totalPages` are 90, but that's not always true. For instance `1/recipes?query=kimchi&cuisine=korean&type=side+dish&page=1` returns only 1 recipe, but still says that the `totalPages` = 90. Making subsequent queries with page > 1 just returns empty responses like:

```json
{
  "data": [],
  "totalPages": 90,
  "page": "3"
}
```

**Comment by ahoskins** [comment]
Looking into it.
